"""Evidence tables for the injected-leak audit, the no-jitter control, the weighing-task rollouts, the codebook sweep, the community-benchmark
certification and the training-cost bookkeeping, generated from the ledgers only.  Usage: python isaac/analysis/report_audit_external.py > report_audit_external.md"""
import os, re, json, glob, math
from collections import defaultdict
import numpy as np
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."); RES = os.path.join(ROOT, "isaac/cluster_results/results"); EV = os.path.join(ROOT, "isaac/cluster_results/eval"); EVH = os.path.join(ROOT, "isaac/cluster_results/eval_hybrid")
def rows(grid):
    f = os.path.join(RES, grid + ".jsonl"); out = {}
    for l in (open(f) if os.path.exists(f) else []):
        r = json.loads(l)
        if "per_t" in r: out[json.dumps({k: v for k, v in r["args"].items() if k not in ("out", "save_codes", "save_model")}, sort_keys=True)] = r
    return list(out.values())
def idx(r, n): return [i for i, q in enumerate(r["phases"]) if q == n]
def full(r):
    p = r["per_t"]; need = [h > 1e-9 for h in p["H(Gam|O)"]]; needg = [h > 1e-9 for h in p["H(G|O)"]]
    mem = [i for i in idx(r, "gap1") + idx(r, "gap2") if need[i]]; act = [min(j) for j in ([i for i in idx(r, "grasp") if needg[i]], [i for i in idx(r, "place") if needg[i]]) if j]
    return bool(mem) and all(p["S_Gam"][i] > 0.9 for i in mem) and all(p["S_G"][i] > 0.9 for i in act)
def pm(r, key, ph): v = [r["per_t"][key][i] for i in idx(r, ph)]; return float(np.nanmean(v)) if v else float("nan")
def ev(r, base=EV):
    f = os.path.join(base, os.path.basename(r["args"]["save_model"])[:-3], "summary.json"); return json.load(open(f)) if os.path.exists(f) else None
mean = lambda xs: float(np.mean(xs)) if len(xs) else float("nan")
print("# Evidence tables: leak audit, no-jitter control, weighing rollouts, codebook sweep, community benchmarks, training cost (generated by isaac/analysis/report_audit_external.py; do not edit by hand)\n\nGate = full-trajectory diagnostic of Section 3 unless stated; closed loop = 128 episodes per policy.\n")

# ---------------------------------------------------------------- R5-6 injected leak
L = rows("leak")
if L:
    print("\n## Injected-leak audit (A' gap 6)\n\nCorrect means held-out class error below 0.05 at the first place step. Flag A was fixed before the runs; flag B is exploratory. Correct placement paired with a failed sufficiency gate is an empirical signal, not a leakage certificate: correctness permits nonzero error and the full gate also checks the first gap and grasp. Use ruleB_baseline.py for the matched rule B' and clean-data false-alarm rates; direct observation probes test the side-information discrepancy.\n")
    print("| delta (mm) | seeds | behaviourally correct | pass the sufficiency gate | second-gap rate, correct seeds (certified 1.00) | S_Gamma second gap, correct seeds | flag A, fixed in advance (correct AND rate < 0.9) | flag B, post hoc (correct AND NOT sufficient) | action MSE (held-out, all seeds) | closed-loop success | slot accuracy | evaluated |\n|---|---|---|---|---|---|---|---|---|---|---|---|")
    by = defaultdict(list)
    for r in L: by[float(re.search(r"_leak([0-9.]+)$", os.path.basename(r["args"]["data"])).group(1))].append(r)
    for d in sorted(by):
        g = by[d]; ok = [r for r in g if r["per_t"]["class_err_test"][idx(r, "place")[0]] < 0.05]; fl = [r for r in ok if r["summary"]["HC_gap2"] < 0.9]; e = [x for x in (ev(r) for r in g) if x]
        print(f"| {d:g} | {len(g)} | {len(ok)}/{len(g)} | {sum(full(r) for r in g)}/{len(g)} | {mean([r['summary']['HC_gap2'] for r in ok]):.2f} [{min([r['summary']['HC_gap2'] for r in ok] or [float('nan')]):.2f}–{max([r['summary']['HC_gap2'] for r in ok] or [float('nan')]):.2f}] | "
              f"{mean([r['summary']['S_Gam_gap2'] for r in ok]):.2f} | {len(fl)}/{len(ok)} | **{sum(not full(r) for r in ok)}/{len(ok)}** | {mean([r['summary']['mse_test'] for r in g]):.4f} | {mean([x['success'] for x in e]):.2f} | {mean([x['slot'] for x in e]):.2f} | {len(e)}/{len(g)} |")

# ---------------------------------------------------------------- R5-1b no-jitter causal control
N = rows("nojit")
if N:
    print("\n## R5-1b Initial-position intervention and predictive surplus (A' gap 20 recorded without the +-2 cm object jitter)\n\n| dataset | learner | seeds | sufficient | first-gap rate | second-gap rate (theory 1.00) | second-gap surplus H(C\\|Gamma,O) | closed-loop success |\n|---|---|---|---|---|---|---|---|")
    ref = [r for g in ("generic", "generic2") for r in rows(g) if os.path.basename(r["args"]["data"]) == "tier4_gap20" and r["args"].get("distill_target") == "random" and (r["args"].get("distill_w") or 1) == 1 and (r["args"].get("distill_off") or 0) in (0, 0.6)]
    for ds, rs in (("with jitter (original)", ref), ("no jitter", N)):
        for off in (0, 0.6):
            g = [r for r in rs if abs((r["args"].get("distill_off") or 0) - off) < 1e-9]; ok = [r for r in g if full(r)]; e = [x for x in (ev(r) for r in g) if x]
            if g: print(f"| {ds} | event-agnostic, {'not annealed' if off == 0 else 'annealed from 60%'} | {len(g)} | {len(ok)}/{len(g)} | {mean([pm(r, 'H(C|O)', 'gap1') for r in ok]):.2f} | {mean([pm(r, 'H(C|O)', 'gap2') for r in ok]):.2f} | **{mean([pm(r, 'H(C|Gam,O)', 'gap2') for r in ok]):.2f}** | {mean([x['success'] for x in e]):.2f} |")

# ---------------------------------------------------------------- R5-7 weigh: hybrid rollout + longer hold
W = [r for g in ("weigh", "weigh2") for r in rows(g)]
if W and os.path.isdir(EVH):
    print("\n## R5-7a Weighing task, hybrid rollout (scripted expert executes home / approach / weighing; the learned policy observes it, keeps its own memory, and acts from the gap on)\n\n| dataset | learner | N | policies | own rollout: success / side accuracy | hybrid rollout: success / side accuracy | hybrid, offline-sufficient seeds only (n) |\n|---|---|---|---|---|---|---|")
    cells = defaultdict(list)
    for r in W:
        a = r["args"]; h = ev(r, EVH); o = ev(r)
        if h is None or o is None: continue
        lab = "plain -R" if not a.get("distill") else ("task-informed forecast from step 0" if a.get("fc_start") == "zero" else "task-informed forecast")
        gg = idx(r, "gap1"); gr = idx(r, "grasp")[0]; suff = all(r["per_t"]["S_Gam"][i] > 0.9 for i in gg) and r["per_t"]["S_G"][gr] > 0.9
        cells[(os.path.basename(a["data"]), lab, a["n_train"])].append((suff, o, h))
    for k in sorted(cells):
        v = cells[k]; s = [x for x in v if x[0]]
        print(f"| {k[0]} | {k[1]} | {k[2]} | {len(v)} | {mean([x[1]['success'] for x in v]):.2f} / {mean([x[1]['side'] for x in v]):.2f} | **{mean([x[2]['success'] for x in v]):.2f} / {mean([x[2]['side'] for x in v]):.2f}** | {mean([x[2]['success'] for x in s]):.2f} / {mean([x[2]['side'] for x in s]):.2f} ({len(s)}) |")
H8 = rows("weighH8")
if H8:
    print("\n## R5-7b Weighing task with an 8-step hold (4 in the main recording)\n\n| learner | seeds | sufficient (gap + grasp decision) | gap rate (theory 2.00) | closed-loop success / side accuracy |\n|---|---|---|---|---|")
    for lab, sel in (("plain -R", lambda a: not a.get("distill")), ("task-informed forecast from step 0", lambda a: bool(a.get("distill")))):
        g = [r for r in H8 if sel(r["args"])]; suf = [r for r in g if all(r["per_t"]["S_Gam"][i] > 0.9 for i in idx(r, "gap1")) and r["per_t"]["S_G"][idx(r, "grasp")[0]] > 0.9]; e = [x for x in (ev(r) for r in g) if x]
        print(f"| {lab} | {len(g)} | {len(suf)}/{len(g)} | {mean([pm(r, 'H(C|O)', 'gap1') for r in suf]):.2f} | {mean([x['success'] for x in e]):.2f} / {mean([x['side'] for x in e]):.2f} |")

# ---------------------------------------------------------------- R5-9 codebook sweep
K = rows("readoutK")
if K:
    print("\n## R5-9 Codebook size on readout-3 (3-bit requirement, cardinality bound K >= 8; task-informed forecast, 8 seeds per cell; K = 8 and 16 from the paper: 0/24 and 15/24)\n\n| K | M=32 | M=128 | M=512 | total | first-gap rate of sufficient seeds (theory 3.00) | closed-loop success (all seeds) |\n|---|---|---|---|---|---|---|")
    for k in sorted({r["args"]["K"] for r in K}):
        g = [r for r in K if r["args"]["K"] == k]; c = {M: [r for r in g if r["args"]["data"].endswith(f"_M{M}")] for M in (32, 128, 512)}; ok = [r for r in g if full(r)]; e = [x for x in (ev(r) for r in g) if x]
        print(f"| {k} | " + " | ".join(f"{sum(full(r) for r in c[M])}/{len(c[M])}" for M in (32, 128, 512)) + f" | **{len(ok)}/{len(g)}** | {mean([pm(r, 'H(C|O)', 'gap1') for r in ok]):.2f} | {mean([x['success'] for x in e]):.2f} |")

# ---------------------------------------------------------------- R5-10 external certification
cfs = [os.path.join(ROOT, "external/results/cert.jsonl")] + sorted(glob.glob(os.path.join(ROOT, "external/results/cluster/cert.*.jsonl")))
if any(os.path.exists(f) for f in cfs):
    R = [json.loads(l) for f in cfs if os.path.exists(f) for l in open(f)]; runs = [r for r in R if r.get("kind") == "run"]
    print("\n## R5-10 Certified requirement vs learned rate on community benchmarks (environment code unmodified from MIKASA-Base)\n\nThe hidden variable is enumerated by driving the external environment with the scripted oracle; the exact solver certifies (A2), (A4) and transitivity on every instance.  "
          "bsuite MemoryChain: requirement = 0 during the two cue-visible steps, num_bits bits from the first cue-free step until the query, then 1 bit once the query index is shown (only the queried bit still matters), independent of memory_length.  Passive T-maze: 1 bit along the corridor.  "
          "Sufficient = S_Gamma > 0.9 at every step with a positive requirement AND closed-loop success >= 0.99 in the external environment (200 episodes).\n")
    print("| task | delay | certified requirement during the delay (bits) | learner | seeds sufficient | learned rate at mid-delay, sufficient seeds | closed-loop success (all seeds) |\n|---|---|---|---|---|---|---|")
    cells = defaultdict(list)
    for r in runs: cells[(r["task"], r["bits"], r["L"], r["mode"])].append(r)
    for k in sorted(cells):
        g = {r["seed"]: r for r in cells[k]}.values(); ok = [r for r in g if r["sufficient"]]; nm = "bsuite MemoryChain, %d bit%s" % (k[1], "" if k[1] == 1 else "s") if k[0] == "memchain" else "Passive T-maze"
        print(f"| {nm} | {k[2]} | {mean([r['req_mid'] for r in g]):.2f} | {'event-agnostic forecast' if k[3] == 'generic' else 'plain imitation'} | {len(ok)}/{len(list(g))} | {mean([r['rate_mid'] for r in ok]):.2f}" + (f" [{min(r['rate_mid'] for r in ok):.2f}–{max(r['rate_mid'] for r in ok):.2f}]" if ok else "") + f" | {mean([r['success'] for r in g]):.2f} |")

# ---------------------------------------------------------------- R5-8 T-maze variants
tfs = [os.path.join(ROOT, "external/results/tmaze.jsonl")] + sorted(glob.glob(os.path.join(ROOT, "external/results/cluster/tmaze.*.jsonl")))
TM = defaultdict(dict)
for f in tfs:
    for l in (open(f) if os.path.exists(f) else []):
        r = json.loads(l)
        if r["steps"] == 5000: TM[(r["mode"], r["L"])][r["seed"]] = r
if any(k[0] in ("rf", "scaffold", "gru4", "gru8") for k in TM):
    names = [("gru", "GRU policy, 128-d continuous state"), ("gru8", "GRU policy, 8-d state"), ("gru4", "GRU policy, 4-d state"), ("plain", "compact K=16 carrier, plain imitation"), ("generic", "compact carrier + event-agnostic forecast"),
             ("rf", "compact carrier + -RF (future decoder with future observations)"), ("scaffold", "compact carrier + annealed continuous scaffold")]
    Ls = sorted({k[1] for k in TM}); print("\n## R5-8 Passive T-maze, additional learners (5000 steps; seeds solved in closed loop / runs, mean success in parentheses)\n\n| learner | " + " | ".join(f"L={L}" for L in Ls) + " |\n|---|" + "---|" * len(Ls))
    for m, nm in names:
        print(f"| {nm} | " + " | ".join((f"{sum(x['success'] >= 0.99 for x in TM[(m, L)].values())}/{len(TM[(m, L)])} ({mean([x['success'] for x in TM[(m, L)].values()]):.2f})" if (m, L) in TM else "--") for L in Ls) + " |")

# ---------------------------------------------------------------- R5-5 cost bookkeeping
T = rows("timing")
if T:
    print("\n## R5-5 Training and deployment cost (A' gap 20, one B200; wall-clock of the forecaster measured in grid `timing`, student / baselines = medians of the 10 000-step ledgers)\n")
    for r in T:
        fc = r.get("fc") or {}; print(f"- forecaster ({fc.get('target')}, {fc.get('fc_steps')} steps, {fc.get('fc_params')} parameters): {fc.get('fc_secs', float('nan')):.0f} s; student parameters {fc.get('student_params')}")
for extra in ("analysis_surplus_decomposition.md", "analysis_stochastic_expert.md", "analysis_W4_bounds_extra.md"):
    print(f"\nSee also `results_md/{extra}`." if os.path.exists(os.path.join(ROOT, "results_md", extra)) else "")
