"""Learning-control diagnostic figure.  (a) the full-history triangle on A': fraction of seeds learning the memory-dependent action (teacher-forced)
per carrier at gap 6/10/20 and P-I M16/M32; (b) P(sufficient) vs reveal->use distance for the unsupervised sole-carrier learners on A'
(320 runs) with the pooled logistic fit; (c) the oracle-Gamma control (same K=16 carrier, privileged join head, training only).
Usage: python isaac/fig4_barrier.py isaac/cluster_results/results/*.jsonl"""
import sys, json, os, collections
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__))); import figstyle; figstyle.main(); P = figstyle.PALETTE
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
from scipy.optimize import minimize
# ---- (a) triangle (numbers from the ledger / Table fullhist; first-divergent-step class error < 0.1, 8 seeds)
cells = ["gap 6", "gap 10", "gap 20", "$M{=}16$", "$M{=}32$"]
tri = [("Transformer, full history", [8, 8, 8, 8, 8], P["alt"], ""), ("GRU, continuous state", [8, 5, 0, 3, 5], P["amber"], ""),
       ("discrete $K{=}16$, unsupervised", [3, 2, 1, 0, 0], P["ours"], ""),
       ("+ teacher-state distillation", [2, 0, 0, 0, 1], P["gray"], ""),
       ("+ task-informed forecast", [8, 8, 8, 8, 5], P["purple"], "////"),
       ("+ event-agnostic forecast (frozen)", [8, 7, 8, 6, 7], "#4b2f6b", "")]      # full-trajectory gate; ledgers distill / frozen60 / generic2 (report_supervision.py output)
# ---- (b) rows for the horizon regression (same filter as isaac/horizon_law.py)
rows = []
for f in sys.argv[1:]:
    for l in open(f):
        try: r = json.loads(l)
        except Exception: continue
        a = r.get("args", {}); ds = os.path.basename(a.get("data", "")); ph = r.get("phases")
        if not ph or "gap2" not in ph or not ds.startswith("tier4") or ds.endswith("_px"): continue
        if a.get("variant", "diacritic") not in ("diacritic", "scaffold") or a.get("aux_theta", 0) or a.get("aux_join", 0) or "smoke" in a.get("out", ""): continue
        if os.path.basename(a.get("out", "")).split(".")[0] in ("symin", "symin2w", "symin3", "distill", "dcfut", "horizon16", "taskA_big") or a.get("sym_input", 0) or a.get("distill", "") or a.get("bfs_noobs", 0): continue   # the paper's 320-run pooled set
        rev = max(i for i, p in enumerate(ph) if p == "scan"); d = r["summary"]
        rows.append((ph.index("grasp") - rev, int(d["S_G_grasp"] > 0.9))); rows.append((ph.index("place") - rev, int(d["S_Gam_gap2"] > 0.9 and d["S_G_place"] > 0.9)))
ds_ = sorted({d for d, _ in rows}); Pr = [np.mean([y for d, y in rows if d == dd]) for dd in ds_]; n = [sum(1 for d, _ in rows if d == dd) for dd in ds_]
X = np.array([[1, d] for d, _ in rows], float); y = np.array([yy for _, yy in rows], float)
w = minimize(lambda w: -np.sum(y * (X @ w) - np.logaddexp(0, X @ w)), np.zeros(2), method="BFGS").x
fig, ax = plt.subplots(1, 3, figsize=(figstyle.TEXTW, 1.36), gridspec_kw=dict(width_ratios=[1.55, 1.0, 0.72], wspace=0.42, left=0.075, right=0.99, top=0.88, bottom=0.42))
xs = np.arange(len(cells)); wd = 0.14
for i, (lab, v, c, hatch) in enumerate(tri):
    vals = [np.nan if np.isnan(x) else x / 8 for x in v]
    ax[0].bar(xs + (i - 2.5) * wd, vals, wd * 0.92, color=c, label=lab, hatch=hatch, edgecolor="white" if not hatch else c, linewidth=0.4, alpha=0.95 if not hatch else 0.55)
ax[0].set_xticks(xs); ax[0].set_xticklabels(cells); ax[0].set_ylabel("fraction of seeds\nlearning the action"); ax[0].set_ylim(0, 1.05); ax[0].set_yticks([0, 0.5, 1])
ax[0].set_title("(a) retrieval is easy, commitment is hard (A$'$)", loc="left"); ax[0].grid(axis="x", visible=False)
# (b) pooled observational fit (320 runs, faint) + the controlled 16-seed sweep (E3; beta_2 sufficiency at threshold 0.9, cells from
# the report generated by isaac/analysis/e3_horizon16.py) with Wilson 95% intervals.
dd = np.linspace(0, 36, 100); ax[1].plot(dd, 1 / (1 + np.exp(-(w[0] + w[1] * dd))), color=P["gray"], lw=1.0, alpha=0.9, zorder=2, label=f"pooled fit ({w[1]:.3f}/step)")
ax[1].plot(ds_, Pr, "o", mfc="white", mec=P["gray"], ms=3.0, mew=0.8, zorder=3)
def wilson(k, n, z=1.96):
    p = k / n; c = (p + z * z / (2 * n)) / (1 + z * z / n); h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / (1 + z * z / n); return c - h, c + h
E3 = {"$-$R": [(19, 1), (23, 3), (33, 1)], "$-$RF": [(19, 5), (23, 2), (33, 0)], "scaffold-RF": [(19, 10), (23, 7), (33, 0)]}
for (lab, cells_), col, mk, off in zip(E3.items(), (P["ours"], P["base"], P["purple"]), ("o", "s", "^"), (-0.8, 0.0, 0.8)):
    xs_ = [d + off for d, _ in cells_]; ps = [k / 16 for _, k in cells_]; ci = np.array([wilson(k, 16) for _, k in cells_])
    ax[1].errorbar(xs_, ps, yerr=[np.array(ps) - ci[:, 0], ci[:, 1] - np.array(ps)], fmt=mk, color=col, ms=3.2, capsize=1.5, lw=0.8, zorder=5, label=f"{lab} (16 seeds)")
ax[1].set_xlabel(r"reveal $\to$ first-use distance (steps)"); ax[1].set_ylabel("$P$(sufficient)"); ax[1].set_ylim(-0.03, 1.2); ax[1].set_yticks([0, 0.5, 1]); ax[1].set_xlim(0, 38)
ax[1].set_title("(b) the barrier grows with distance", loc="left")
ax[2].plot([19, 33], [3 / 8, 1 / 8], "o", color=P["ours"], ms=4.5, zorder=4, label="_")
ax[2].plot([19, 33], [8 / 8, 8 / 8], "D", color=P["purple"], ms=4, zorder=5, label="forecast heads (c)")
ax[2].plot([19, 33], [8 / 8, 5 / 8], "*", color=P["amber"], ms=8, zorder=4, label="oracle-$\\Gamma$ head")
ax[2].plot([19], [0 / 8], "x", color=P["gray"], ms=6, mew=1.2, zorder=4, label="4-bit join, oracle head")
ax[2].set_xticks([19, 33]); ax[2].set_xticklabels(["gap 6\n($d$=19)", "gap 20\n($d$=33)"]); ax[2].set_xlim(12, 40); ax[2].set_ylim(-0.08, 1.12); ax[2].set_yticks([0, 0.5, 1])
ax[2].set_ylabel("fraction sufficient"); ax[2].set_title("(c) not capacity: supervision", loc="left")
H, L = ax[0].get_legend_handles_labels(); h1, l1 = ax[1].get_legend_handles_labels(); h2, l2 = ax[2].get_legend_handles_labels(); H += h1 + h2; L += l1 + l2
figstyle.legend_below(fig, H, L, ncol=6, y=-0.09, handlelength=1.1, columnspacing=0.55, handletextpad=0.35, fontsize=5.6)
out = "paper/figs/fig4_barrier.png"; figstyle.save(out); print("fit", w)
